services:
  frontend:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    depends_on:
      - fastapi

  fastapi:
    build:
      context: .
      dockerfile: backend/service/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend/service:/app
